version: "3"
services:
  try-fastify-hellp-api:
    build:
      context: .
      dockerfile: ./services/Dockerfile
      args:
        service: "hello"
    container_name: try-fastify-hello-api
    ports:
      - "3000:3000"
